### ISSUE TITLE
telive on arm

### ISSUE THREAD

**Issue by y1ds** [sq5bpf/telive#13]
Im having some troubles getting the telive scanning feature to work on arm.
I have followed the instructions in the documentation, and on my x86 machine it works as expected. 
The xmlrpc example works perfectly.
However when I try exactly the same on arm (raspbery pi and pandaboard) scanning doesnt seem to work.
The tuner works and accepts commands via xmlrpc, I can change the frequency from within telive, it retunes and receives tetra data. When I try to start scanning (q) nothing happens tho. The freqeuncy stays the same and no xmlrpc messages are being received by the tuner. 
If you could give me some clues on how to investigate this further that would be apreciated.

**Comment by sq5bpf** [comment]
you probably have a problem with gnuradio on arm. please don't run volk_profile and delete ~/.volk . gnuradio will not run optimal, but it will run

i've had this problem on raspbian 8, but i think this is solved in latest gnuradio from backports

**Comment by y1ds** [comment]
I did not run volk_profile and dont have ~/.volk. I tried installing gnuradio and all the libgnuradios from debian jessie backports, still the same problem.

**Comment by sq5bpf** [comment]
if you can manually tune and you are receiving tetra traffic, then i have absolutely no idea what could be the problem. i'd try to attach strace to the processes and see if the xmlrpc are sent/received

also try to do a default minimum install of raspbian 8, install everything from the telive_install.sh script and try the 1-channel headless setup. this has worked for me last time i've tried it

**Comment by sq5bpf** [comment]
no followup, i'm closing the issue
